apiVersion: apps/v1
kind: Deployment

metadata:
  name: transunion-dashboard

spec:
  replicas: 1

  selector:
    matchLabels:
      app: transunion-dashboard

  template:
    metadata:
      labels:
        app: transunion-dashboard

    spec:
      containers:
      - name: transunion-dashboard
        image: surya2411/transunion-dashboard:latest

        ports:
        - containerPort: 8501
